version: "3.7"

services:
  fastapi:
    container_name: fastapi
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - .:/code
    ports:
      - "8000:8080"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:4.2.22
